Flavor.create!([
  {name: "DoubleCheck", handle: "DOUBLECHECK", terms_url: "http://bit.ly/2jfR9vU"},
  {name: "The 99", handle: "THE99", terms_url: "http://bit.ly/2jgDhky"},
  {name: "Pocket Squad", handle: "POCKETSQUAD", terms_url: "http://bit.ly/2jtx4Se"},
  {name: "Text A Coach", handle: "TEXTACOACH", terms_url: "http://bit.ly/2gfjm0f"}
])

AdminUser.create!([
  {email: "test@test.com", password: "test123", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 15, current_sign_in_at: "2017-03-27 05:52:02", last_sign_in_at: "2017-01-17 02:21:34", current_sign_in_ip: "47.156.246.16", last_sign_in_ip: "47.147.48.51"}
])

Agent.create!([
  {name: "Matt W.", job_title: "CFP", email: "test@test.com"},
  {name: "Daniel F.", job_title: "CPA", email: "test@test.com"},
  {name: "Jena P.", job_title: "CFP", email: "test@test.com"},
  {name: "Karen", job_title: "CFP", email: "test@test.com"}
])

User.create!([
  {phone_number: "555-555-1212", name: "Barry L.", email: "", city: "New York", state: "NY", terms: nil},
  {phone_number: "555-555-1212", name: "Ariela S.", email: "", city: "Yonkers", state: "NY", terms: nil},
  {phone_number: "555-555-1212", name: "Debbie L.", email: "", city: "Staten Island", state: "NY", terms: nil},
  {phone_number: "555-555-1212", name: "Ed M.", email: "", city: "Lousiville", state: "KY", terms: nil},
  {phone_number: "555-555-1212", name: "Ben J.", email: "", city: "Dayton", state: "OH", terms: nil},
  {phone_number: "555-555-1212", name: "Cooper C.", email: "", city: "Washington", state: "D.C.", terms: nil},
  {phone_number: "555-555-1122", name: "John L.", email: "", city: "Brooklyn", state: "NY", terms: nil},
  {phone_number: "555-555-1212", name: "Jared G.", email: "", city: "Oakland", state: "CA", terms: nil},
  {phone_number: "555-555-1212", name: "Natalia L.", email: "", city: "Oakland", state: "CA", terms: nil},
  {phone_number: "555-555-1212", name: "Mario P.", email: "", city: "Dallas", state: "TX", terms: nil},
  {phone_number: "555-555-1212", name: "Regina B.", email: "", city: "Ashville", state: "NC", terms: nil},
  {phone_number: "555-555-1212", name: "Sam S.", email: "", city: "Philadelphia", state: "PA", terms: nil},
  {phone_number: "555-555-1212", name: "Lauren S.", email: "", city: "Boston", state: "MA", terms: nil},
  {phone_number: "555-555-1212", name: "Frank D.", email: " ", city: "New York", state: "NY", terms: nil},
  {phone_number: "555-555-1212", name: "John W.", email: " ", city: "Los Angeles", state: "CA", terms: nil}
])

Conversation.create!([
  {agent_id: 2, user_id: 2, summary_question: "What are my options for having friends/family help with my bills?", summary_answer: "There's several options, from informal to legally binding. We can find one that works for you. ", last_message_at: "2016-11-08 09:05:12", flavor_id: 1},
  {agent_id: 1, user_id: 1, summary_question: "What effect will shopping for an auto loan have on my credit?", summary_answer: "In most cases, it will have little to no impact on your credit score(s).", last_message_at: "2016-11-07 14:02:11", flavor_id: 1},
  {agent_id: 4, user_id: 13, summary_question: "Is there a limit to how many times a debt collector can call me?", summary_answer: "No there isn't. But we can talk about other ways to stop calls if you're getting them.", last_message_at: "2016-11-07 11:10:30", flavor_id: 1},
  {agent_id: 3, user_id: 14, summary_question: "I owe more on my current loan than my current vehicle is worth. What do I need to know if I buy a new vehicle?", summary_answer: "You can roll the balance into the new auto loan, but make sure you understand how it affects the total cost of the new loan.", last_message_at: "2016-11-05 13:10:00", flavor_id: 1},
  {agent_id: 3, user_id: 15, summary_question: "How quickly can I get money after I deposit a check?", summary_answer: "While the law has a maximum time, unfortunately it varies by bank. ", last_message_at: "2016-11-10 14:10:11", flavor_id: 1},
  {agent_id: 3, user_id: 8, summary_question: "How much should I contribute to my 401k?", summary_answer: "Start anywhere, but saving 10% of your earnings is a good goal.", last_message_at: "2016-11-01 00:00:00", flavor_id: 1},
  {agent_id: 1, user_id: 1, summary_question: "What is a credit card interest rate? ", summary_answer: "A credit card’s interest rate is the price you pay for borrowing money", last_message_at: "2016-11-05 10:20:01", flavor_id: 1},
  {agent_id: 1, user_id: 2, summary_question: "What does it mean to rehabilitate a student loan?", summary_answer: "It's a way to get a federal student loan out of debt. Should we walk through how it works in more detail?", last_message_at: "2016-11-10 10:07:08", flavor_id: 1},
  {agent_id: 2, user_id: 1, summary_question: "How do I dispute a charge on my credit card bill?", summary_answer: "You can call the card issuer, but there's information you should mail in too.", last_message_at: "2016-11-10 10:50:02", flavor_id: 1},
  {agent_id: 3, user_id: 8, summary_question: "When's a good age to open a savings account for my child?", summary_answer: "Any age really.", last_message_at: "2016-11-15 11:12:09", flavor_id: 1},
  {agent_id: 4, user_id: 9, summary_question: "Are there any student loan breaks for public service?", summary_answer: "Yes! Happy to help you figure out if you qualify and how to get them. ", last_message_at: "2016-11-10 17:15:00", flavor_id: 1},
  {agent_id: 4, user_id: 10, summary_question: "What costs and fees could I expect with a payday loan?", summary_answer: "Usually a fixed fee on the amount you borrow, like $15 per $100 borrowed (equal to about 400% interest).", last_message_at: "2016-10-25 15:04:02", flavor_id: 1},
  {agent_id: 4, user_id: 11, summary_question: "What is a payday loan?", summary_answer: "A short-term loan, generally for $500 or less, due on your next payday and with high interest. ", last_message_at: "2016-11-01 07:00:02", flavor_id: 1},
  {agent_id: 4, user_id: 12, summary_question: "What is a remittance transfer?", summary_answer: "It refers to a way of electronically transferring money transfers from the United States to recipients abroad.", last_message_at: "2016-11-04 10:05:10", flavor_id: 1},
  {agent_id: 3, user_id: 5, summary_question: "Does my credit score matter? ", summary_answer: "Yes, when applying for a loan, credit card, or sometimes renting or a new job.", last_message_at: nil, flavor_id: 1},
  {agent_id: 3, user_id: 4, summary_question: "I’m having a hard time paying my student loans. What can I do?", summary_answer: "You may be able to change from a standard plan to income based repayment. Can I ask some questions to help you figure this out?", last_message_at: nil, flavor_id: 1},
  {agent_id: 3, user_id: 7, summary_question: "How do I know if I have a bad credit score?", summary_answer: "Often credit scores less than 620 are considered poor, but we can work and improve on anything. ", last_message_at: nil, flavor_id: 1},
  {agent_id: 3, user_id: 3, summary_question: "How can I create a budget that will help me achieve my goals?", summary_answer: "Hi Sam, thanks for asking!  Budgets aren’t hard to make, just hard to stick to at first. We can make one together. ", last_message_at: nil, flavor_id: 1},
  {agent_id: 3, user_id: 6, summary_question: "How much should I save for retirement each month?", summary_answer: "Start small and go from there. Can I ask a few questions to help you find the right amount?", last_message_at: nil, flavor_id: 1},
  {agent_id: 3, user_id: 2, summary_question: "How can I explain to my children where money comes from?", summary_answer: "Depends on their age. We can discuss ideas depending on how old yours are.", last_message_at: nil, flavor_id: 1}
])

Message.create!([
  {conversation_id: 22, direction: 1, message: "3 and 4 years old"},
  {conversation_id: 22, direction: 2, message: "If they are 3-5 years old, you can start by explaining that the money your family spends and saves comes from working. It’s hard for such young kids to understand “work”, so you can describe the jobs you, your spouse and others in your family go to every day. Walk through the neighborhood or town and point out people working, like the bus driver or police officer. Does your town have small businesses or restaurants?"},
  {conversation_id: 22, direction: 1, message: "Yes. We have some pizza places, and corner stores. My kids love a bagel shop in town, too."},
  {conversation_id: 22, direction: 2, message: "Awesome. It may help to explain that some people start their own businesses like stores or restaurants – maybe even use the bagel shop as your example! Try explaining that business owners make money through profit, by buying goods or resources at one price and charging customers enough to cover their costs, time, and a return on their investment."},
  {conversation_id: 22, direction: 1, message: "Ok. What do you think about me paying my kids to do chores to help them understand where money comes from?"},
  {conversation_id: 22, direction: 2, message: "That sounds like a great idea. You could also encourage your children to earn their own money by setting up a lemonade or cookie stand, so that they understand how hard it may be to get money when you're selling to people outside of your friends and family."},
  {conversation_id: 20, direction: 1, message: "When I explain savings accounts, how can I explain banks and credit unions to my children?"},
  {conversation_id: 20, direction: 2, message: "Explain that we use banks and credit unions to keep our money safe and to receive interest. Even younger children will understand the safety and security part, but you might want to save a detailed explanation of compounding interest, or how our banking system works, until they’re able to get it. "},
  {conversation_id: 20, direction: 1, message: "What if my kids ask why banks pay us for keeping our money safe?"},
  {conversation_id: 20, direction: 2, message: "Great question. You can explain simply that banks and credit unions use our savings to make loans to other people. They charge those customers a little extra when they pay the money back, and we get a portion of that.  You can also explain that the deposits we put into a bank or credit union are insured through the federal government."},
  {conversation_id: 19, direction: 1, message: "Yes, I do."},
  {conversation_id: 19, direction: 2, message: "If you have federal Direct Loans, including Direct Consolidation Loans, you may be eligible for Public Service Loan Forgiveness, also called PSLF.  I can also tell you about some other opportunities if that helps!"},
  {conversation_id: 19, direction: 1, message: "Yes, please do."},
  {conversation_id: 19, direction: 2, message: "If you make 10 years of qualified monthly payments while serving in the military or employed at a government or non-profit entity, you may be able to get the balance of your loans forgiven. If you have older federal loans originated under the Federal Family Educational Loan (FFEL) program or the Perkins loan program, you may be able to consolidate those loans into a new Direct Loan to qualify for Public Service Loan Forgiveness. There are other benefits available to service members, teachers, Perkins loan borrowers and others. The U.S. Department of Education offers more information for borrowers working in public service."},
  {conversation_id: 18, direction: 1, message: "So what if I borrow $300 before my next payday?"},
  {conversation_id: 17, direction: 1, message: "Is there a catch to it? What else do I need to know?"},
  {conversation_id: 17, direction: 2, message: "Payday loans generally have three features:  The loans are for small amounts. The loans typically come due your next payday. You must give lenders access to your checking account or write a check for the full balance in advance that the lender has an option of depositing when the loan comes due."},
  {conversation_id: 14, direction: 1, message: "I keep hearing different words that sound similar to \"remittance transfer\". Are there other words for it?"},
  {conversation_id: 14, direction: 2, message: "Yes, remittance transfers are commonly known as “international wires,” “international money transfers,” or “remittances”. "},
  {conversation_id: 14, direction: 1, message: "Are there any federal protections that apply when I send money abroad?"},
  {conversation_id: 8, direction: 2, message: "Once your credit card company receives your letter, it has 30 days to confirm it received it. The company has two complete billing cycles after receipt of notice from consumer (but no more than 90 days) to investigate. You don’t have to pay the disputed amount while the card issuer is investigating. You can’t be required to pay interest or other charges relating to the disputed amount during the investigation. If you pay the entire undisputed amount of your bill on time, the card issuer can’t treat your payment as late."},
  {conversation_id: 5, direction: 2, message: "For credit cards, the interest rates are typically stated as a yearly rate, called the annual percentage rate (APR).  On most cards, you can avoid paying interest on purchases if you pay your balance in full each month."},
  {conversation_id: 7, direction: 1, message: "Yes, please do."},
  {conversation_id: 14, direction: 2, message: "Yes! Under federal law, many money transmitters, banks and credit unions and possibly other types of financial services companies qualify as “remittance transfer providers.” They must generally provide consumers certain information before they make remittance transfers. This includes information about the exchange rate, fees and taxes they collect from you, fees charged by the company’s agents abroad and certain other institutions involved in the transfer process, the amount of money expected to be delivered, not including foreign taxes or certain fees charged to the recipient, and if appropriate, a statement that additional foreign taxes and fees may be deducted from the remittance transfer."},
  {conversation_id: 12, direction: 1, message: "How can I do that?"},
  {conversation_id: 12, direction: 2, message: "Carefully look at the total cost of the new loan including the amount borrowed, the annual percentage rate (APR), the interest rate, the loan term (in months), and the monthly payment – before you agree to anything. If you don’t roll the amount you still owe on your old vehicle into the new loan, and keep your current vehicle while buying a new one, then you will have two loans and two monthly payments to make. Either way, you may want to consider whether it makes sense to go through with the transaction and purchase the next vehicle if you still owe money on your trade-in. "},
  {conversation_id: 12, direction: 1, message: "What if I owe more than my current vehicle is worth?"},
  {conversation_id: 24, direction: 2, message: "Hi Sam, thanks for asking!  Budgets aren’t that hard to make but they can be difficult to stick to when you’re getting started.  Having goals will help you allocate your funds better and make it a lot easier.  Have you ever created a budget before, or shall we start at the beginning?"},
  {conversation_id: 24, direction: 1, message: "I’ve never made a budget before."},
  {conversation_id: 12, direction: 2, message: "If you owe more than your current vehicle is worth – sometimes referred to as “negative equity” – you should consider whether you can afford a new vehicle.  To find out if you have negative equity, you should look up the approximate value of your current vehicle using websites such as the Consumer Reports, Edmunds, Kelley Blue Book, NADA Guides, and online classifieds. You may also find these and other resources at your local library. Look up the “private sale” value, because that’s what you can get if you sell your vehicle to an individual. Look up “Trade In to Dealer” if you want to see a range of prices for similar vehicles. Then call your lender to find out how much you still owe on your loan.  A dealer may offer to “roll in” the balance of your old loan into a loan for a new vehicle. This is called a “negative trade-in,” because the trade-in adds to the cost of the new loan, rather than reducing it. This might make the new loan unaffordable. Be very careful to make sure you understand the total cost of the new loan and the monthly payments – and the loan term (in months) – before you agree to anything."},
  {conversation_id: 11, direction: 1, message: "And what happens if I apply for multiple loans?"},
  {conversation_id: 11, direction: 2, message: "In some cases, applying for multiple loans over a long period of time can lower your credit score(s). Generally any requests or \"inquiries\" by these lenders for your credit score(s) that took place within a time span ranging from 14 days to 45 days will only count as a single inquiry, depending on the credit scoring model used. You can minimize any negative impact to your credit by doing all of your shopping in a short amount of time. You could save hundreds or even thousands of dollars by shopping for the best rate and terms on a loan.  "},
  {conversation_id: 11, direction: 1, message: "I don't really understand. Can you use an example to explain that? "},
  {conversation_id: 11, direction: 2, message: "Of course. Let's say you are looking around for an auto loan and you authorize five lenders to check your credit score(s) within a 14 day time span. All those inquiries should count as one inquiry.  If you shop for a mortgage loan at the same time you are shopping for an auto loan, the shopping you do for those two loans should count as two separate inquiries.  And don't worry about all those promotional offers for credit cards impacting your credit score(s). These promotional offers do not affect your credit score(s)."},
  {conversation_id: 10, direction: 1, message: "What about other people? Are there organized programs that provide help?"},
  {conversation_id: 10, direction: 2, message: "Yes! There are organized programs that provide trained staff members or volunteers to help. To locate a money management program in your area, try contacting your local Area Agency on Aging (www.n4a.org). If you get help from a money management program, check on whether the program has insurance or bonding so your money is protected in a worst case scenario involving mismanagement or theft by the person assisting you."},
  {conversation_id: 9, direction: 1, message: "I don't really understand. Can you use an example to explain that? "},
  {conversation_id: 9, direction: 2, message: "Of course. Generally, if you deposit a check for $200 or less in person to a bank employee, you can access the full amount the next business day. If you deposit more than $200, you can access $200 the next business day, and the rest of the money the second business day."},
  {conversation_id: 9, direction: 1, message: "What if I need the money from a specific check?"},
  {conversation_id: 9, direction: 2, message: " If you need the money from a particular check, you can ask the teller when the funds will become available. A receipt showing your deposit does not mean that the money is available for you to use."},
  {conversation_id: 9, direction: 1, message: "The last time I deposited a check at the bank, they told me I missed the cut off time. What does that mean?"},
  {conversation_id: 9, direction: 2, message: "Your bank or credit union has a cut-off time for what it considers the end of the business day. If you make a deposit after the cut-off time, the bank or credit union can treat your deposit as if it was made on the next business day. A bank or credit union’s cut-off time for receiving deposits can be no earlier than 2:00 p.m. at physical locations and no earlier than noon at an ATM or elsewhere."},
  {conversation_id: 8, direction: 1, message: "How do I send a billing error notice?"},
  {conversation_id: 8, direction: 2, message: "You should follow the instructions on your monthly credit card statement for where and how to send a billing error notice. The address where you should send this notice is usually different from the payment address. "},
  {conversation_id: 8, direction: 1, message: "What should I write in the letter?"},
  {conversation_id: 8, direction: 2, message: "Your name and account number, the dollar amount of the charge you're disputing, and an explanation of the reason why you think an error was made."},
  {conversation_id: 8, direction: 1, message: "And how long will this all take?"},
  {conversation_id: 1, direction: 1, message: "Thanks, and yes! My employer offers matchings."},
  {conversation_id: 1, direction: 2, message: "Then try to contribute at least enough to get the match. It would be very useful!"},
  {conversation_id: 5, direction: 1, message: "What about an APR?"},
  {conversation_id: 13, direction: 1, message: "Kind of. A debt collector keeps calling me."},
  {conversation_id: 7, direction: 2, message: "In order to rehab a loan, you must make 9 monthly payments within 20 days of the due date over a period of 10 months.    Are your federal student loans currently in default?"},
  {conversation_id: 23, direction: 1, message: "How much should I save for retirement each month?"},
  {conversation_id: 23, direction: 2, message: "Hi Jake, thanks for asking! The answer is different for everyone. Do you mind if I ask you a few questions?"},
  {conversation_id: 23, direction: 1, message: "Sure."},
  {conversation_id: 23, direction: 2, message: "Great. Do you know if you have a retirement plan offered through your employer?"},
  {conversation_id: 23, direction: 1, message: "I do, but I am not using it yet."},
  {conversation_id: 23, direction: 2, message: "Thanks.  Sometimes employers offer matching amounts.  If you save, then they also contribute money on your behalf.  It’s very helpful, as a start, to try to contribute enough to get the full match (free money).  Do you know if your employer offers a match?"},
  {conversation_id: 23, direction: 1, message: "I don’t know.  I think they do."},
  {conversation_id: 23, direction: 2, message: "Usually your manager or someone in Human Resources can tell you about the plan details.  They usually have enrollment information in an easy to read format.  But, they also have something called a Summary Plan Description that you can ask for that will tell you all of the details.  Why don’t you ask tomorrow at work, and then text us back and we can help figure out how to get you enrolled, answer more questions, and get you started!"},
  {conversation_id: 23, direction: 1, message: "Sounds good. Thanks."},
  {conversation_id: 24, direction: 1, message: "How can I create a budget that will help me achieve my goals?"},
  {conversation_id: 24, direction: 2, message: "Great.  Then let’s start at the beginning.  In order to budget, you need to start with your income.  Knowing how much you get paid tells you how much you have to put towards your bills and also to save towards any of your goals. You also need to decide for what time frame you want to create a budget.  Most people make a monthly budget, but some people prefer to make one for each time they get paid, whether weekly, bi-weekly, twice a month, etc.  Do you know your income, and what timeframe do you think might work best for you?"},
  {conversation_id: 24, direction: 1, message: "I have my paystubs.  What number do I use?  And, I think monthly."},
  {conversation_id: 24, direction: 2, message: "Ok...If you are going with a monthly budget, then start by looking at your paycheck to find your net pay (also known as your take home pay).  Do you see that?  And, do you get paid weekly or bi-weekly (every two weeks) or on come other schedule?"},
  {conversation_id: 24, direction: 1, message: "I get paid weekly."},
  {conversation_id: 24, direction: 2, message: "Great.  So you will need to look at a calendar.  Some months you will get paid 4 times and others 5 times.  As an example, for January 2017, if you get paid every Friday, then you will get 4 checks in the month.  "},
  {conversation_id: 24, direction: 1, message: "I do get paid on Fridays!"},
  {conversation_id: 24, direction: 2, message: "Great.  So, for January 2017, you will take your net pay weekly, and multiply that by 4 to get your total income for the month. Does that make sense?"},
  {conversation_id: 24, direction: 1, message: "It does."},
  {conversation_id: 24, direction: 2, message: "Ok.  The next step is to start listing your expenses.  You need to include everything along with the goals you have.  You might have rent or mortgage, utilities, groceries, public transit or car expenses, etc.  You need to list them all out and figure out what you spend.  Some things are easier - what we call fixed expenses, and the amount doesn’t change. Like rent.  And some things are harder - what we call variable expenses, and the amount can vary.  Like groceries.  "},
  {conversation_id: 24, direction: 1, message: "I can do that, but it’s going to take some time. "},
  {conversation_id: 24, direction: 2, message: "No worries.  Why don’t you work on that, and then let us know when you’re ready for the next step!  "},
  {conversation_id: 24, direction: 1, message: "I will.  Thanks for your help."},
  {conversation_id: 25, direction: 1, message: "How do I know if I have a bad credit score?"},
  {conversation_id: 25, direction: 2, message: "Hi, thanks for asking!  Credit scores range from 300-850, with 300 being low and 850 being high.  Credit scores less than 620 are generally considered to be poor and could prevent you from qualifying for a loan, or credit card, or even from renting an apartment.  Do you know what your score is?  We can help you check your score, and help you work on improving it!"},
  {conversation_id: 25, direction: 1, message: "I don’t know my score.  I’ve never checked."},
  {conversation_id: 25, direction: 2, message: "No worries.  Checking your score is pretty easy these days, and it’s free.  You can go to www.creditkarma.com or to www.nerdwallet.com sign up, answer some questions, and see it right away.  Why don’t you take a look and then let us know and we can continue our chat."},
  {conversation_id: 25, direction: 1, message: "Ok.  I will check it and get back to you."},
  {conversation_id: 26, direction: 1, message: "I’m having a hard time paying my student loans, and don’t know what to do. "},
  {conversation_id: 26, direction: 2, message: "Hi Greg, thanks for asking!  Student loans can be scary.  Have you contacted your lender to see what your options are?  There are many different federal repayment plans, and some of them base payments on your income to make them more affordable. You may also be able to get a forbearance or deferment as you work through things to give you some breathing room.  Do you know what payment plan you are currently on? "},
  {conversation_id: 26, direction: 1, message: "I don’t know what payment plan I’m on, but it was whatever came on the statement after I left school."},
  {conversation_id: 26, direction: 2, message: "I can’t be 100% certain without seeing your documents, but it’s likely that you are on what is known as the standard repayment plan - where your loans will be paid off in full at the end of ten years, but as a result, your payments are higher.  When you call your lender, ask if you are on the standard repayment plan, and then if you are, ask if you are eligible for Pay as You Earn or another income based repayment.  Changing to one of the income based plans will lower the payment, sometimes significantly.  If you want to estimate things before you call, you can use the calculator here:  https://studentloans.gov/myDirectLoan/mobile/repayment/repaymentEstimator.action"},
  {conversation_id: 27, direction: 1, message: "Does my credit score matter? "},
  {conversation_id: 27, direction: 1, message: "I have, but it isn’t great."},
  {conversation_id: 27, direction: 2, message: "Credit scores definitely matter when applying for a loan or for a credit card, and depending on where you live, they can also be checked by employers when you apply for a job or be a factor in the amount you pay for car insurance.  Have you ever checked your credit score?"},
  {conversation_id: 27, direction: 2, message: "Don’t worry.  Many people have encountered difficulties with credit.  It can get better!  Do you mind if I ask, are you behind on some payments, or struggling to make payments?"},
  {conversation_id: 27, direction: 1, message: "I have some old accounts that I never paid, but am not behind on my rent or utilities, or things that matter right now."},
  {conversation_id: 27, direction: 2, message: "Great news.  Glad to hear that you are doing well right now.  Do you know if those old accounts are still on your credit report?  Are any collection agencies calling you to request payment?"},
  {conversation_id: 27, direction: 1, message: "Great news.  Glad to hear that you are doing well right now.  Do you know if those old accounts are still on your credit report?  Are any collection agencies calling you to request payment?"},
  {conversation_id: 27, direction: 2, message: "Let’s start by looking at your credit report.  You can go to www.annualcreditreport.com to review your report for free.  You’ll have to log in and provide some information to verify your identity in order to access your reports.  There is no charge for the report.  Do not agree to pay for a score.  We don’t need that right now.  You can request a report from each of the three major credit bureaus:  Transunion, Equifax and Experian, but let’s start with just one.  After you do that, we can chat some more about how to read it and next steps.  How does that sound?"},
  {conversation_id: 27, direction: 1, message: "I don’t know.  It seems hard."},
  {conversation_id: 27, direction: 2, message: "Depending on where you live, you may be able to set up a time to meet in person with a financial coach who can help you review your credit report and make a plan in person.  How does that sound?"},
  {conversation_id: 27, direction: 1, message: "Is it expensive?"},
  {conversation_id: 27, direction: 2, message: "No, if available in your area, then most in-person  financial coaching is provided by non-profit organizations at no charge.  If you don’t mind letting me know where you live, then I can direct you."},
  {conversation_id: 27, direction: 1, message: "I’m in Miami."},
  {conversation_id: 27, direction: 2, message: "Great.  Then there are a couple of possibilities for in person coaching where you can get help looking at your credit reports and making a plan to make your credit better.  Here are the links.  Take a look and let me know how these might work for you.  www.catalystmiami.org and http://miamifinancialstability.org/"},
  {conversation_id: 27, direction: 1, message: "I will contact one of them to make an appointment.  Thanks!  "},
  {conversation_id: 11, direction: 2, message: "\tShopping for the best deal on an auto loan will generally have little to no impact on your credit score(s). The benefit of shopping will far outweigh any impact on your credit."},
  {conversation_id: 1, direction: 1, message: "How much should I contribute to my 401k?"},
  {conversation_id: 1, direction: 2, message: "Saving 10% of your earnings for retirement is the general goal. Does your employer offer matching?"},
  {conversation_id: 5, direction: 1, message: "What is a credit card interest rate?"},
  {conversation_id: 5, direction: 2, message: "A credit card’s interest rate is the price you pay for borrowing money"},
  {conversation_id: 7, direction: 1, message: "What does it mean to rehabilitate a student loan?"},
  {conversation_id: 7, direction: 2, message: "Rehabilitating your loan is one way to get a federal student loan out of default.  Would it be helpful to walk you through how to rehab a loan?"},
  {conversation_id: 8, direction: 1, message: "How do I dispute a charge on my credit card bill?"},
  {conversation_id: 8, direction: 2, message: "You can call the card issuer. However, in order to protect your rights you must also send a written billing error notice to the card issuer within a certain period of time."},
  {conversation_id: 9, direction: 1, message: "How quickly can I get money after I deposit a check?"},
  {conversation_id: 9, direction: 2, message: "Each bank or credit union has its own rules as to when it will let you access money after you deposit a check but federal law establishes the maximum length of time a bank or credit union can make you wait."},
  {conversation_id: 10, direction: 1, message: "I would like to be able to have my friend or family member help with my bill-paying and banking. What are my options?"},
  {conversation_id: 10, direction: 2, message: "You have several options, including opening specific types of checking accounts or creating specific legal documents that give another person the power to handle your money."},
  {conversation_id: 11, direction: 1, message: "What effect will shopping for an auto loan have on my credit?"},
  {conversation_id: 12, direction: 1, message: "I owe more on my current loan than my current vehicle is worth. What do I need to know if I buy a new vehicle?"},
  {conversation_id: 12, direction: 2, message: "If you are considering rolling the balance of the old auto loan into your new auto loan, make sure you understand how this will affect the total cost of your new loan."},
  {conversation_id: 13, direction: 2, message: "Federal law doesn’t give a specific limit on the number of calls a debt collector can place to you. Have you been experiencing issues?"},
  {conversation_id: 14, direction: 1, message: "What is a remittance transfer?"},
  {conversation_id: 14, direction: 2, message: "Federal law defines “remittance transfers” to include most electronic money transfers from consumers in the United States through “remittance transfer providers” to recipients abroad."},
  {conversation_id: 17, direction: 1, message: "What is a payday loan?"},
  {conversation_id: 17, direction: 2, message: "A payday loan is a short-term loan, generally for $500 or less, that is typically due on your next payday."},
  {conversation_id: 18, direction: 1, message: "What costs and fees could I expect with a payday loan?"},
  {conversation_id: 18, direction: 2, message: "Payday loans generally charge a fixed fee on the amount you borrow. A fee of $15 per $100 is typical, which equates to an annual percentage rate of almost 400% for a two-week loan."},
  {conversation_id: 18, direction: 2, message: "That’s a $90 charge for borrowing $300 for just a few weeks. In addition, if you don’t repay the loan on time, the lender might charge a late or returned check fee, depending on state law. "},
  {conversation_id: 18, direction: 2, message: "If your loan funds are loaded onto a prepaid debit card, there might be other fees you should take into consideration, such as fees to add the money to the card, fees for checking your balance or calling customer service, fees each time you use the card and/or regular monthly fees. Be sure to read the loan agreement carefully to spot other fees and costs before you take out a loan."},
  {conversation_id: 13, direction: 1, message: "Is there a limit to how many times a debt collector can call me?"},
  {conversation_id: 18, direction: 2, message: "If you need to borrow $300 before your next payday, it would cost you $345 to pay it back, assuming a fee of $15 per $100.  If you renew or roll over your loan, you will be charged another fee and still owe the entire original balance. For example, if you pay a fee renewal or rollover fee of $45 you would still owe the original $300 loan and another $45 fee when the extension is over."},
  {conversation_id: 19, direction: 1, message: "Are there any student loan breaks for public service?"},
  {conversation_id: 19, direction: 2, message: "Yes! Do you have federal Direct Loans?"},
  {conversation_id: 20, direction: 1, message: "When's a good age to open a savings account for my child?"},
  {conversation_id: 20, direction: 2, message: "Your child can start learning to save at any age. Consider opening a savings account for your child as soon as they save more in their piggy bank than you feel comfortable letting them have easy access to."},
  {conversation_id: 22, direction: 1, message: "How can I explain to my children where money comes from?"},
  {conversation_id: 22, direction: 2, message: "This depends on the age of your children. In general, it may be helpful to assure they understand that money comes from working a job. Then, depending on their age, you can explain more or less about where money comes from, variance of jobs, how money is spent, etc. How old are your children?"},
  {conversation_id: 13, direction: 2, message: "I'm sorry to hear that. A debt collector cannot call you repeatedly or continuously to annoy, abuse, or harass you or others who share the number.  You do have a right to tell the debt collector to stop calling you."}
])


ActsAsTaggableOn::Tagging.create!([
  {tag_id: 1, taggable_id: 1, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 2, taggable_id: 1, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 3, taggable_id: 1, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 7, taggable_id: 5, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 8, taggable_id: 5, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 9, taggable_id: 5, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 11, taggable_id: 7, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 12, taggable_id: 7, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 13, taggable_id: 7, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 7, taggable_id: 8, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 14, taggable_id: 8, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 15, taggable_id: 8, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 16, taggable_id: 9, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 17, taggable_id: 9, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 18, taggable_id: 9, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 19, taggable_id: 10, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 20, taggable_id: 10, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 21, taggable_id: 10, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 22, taggable_id: 11, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 23, taggable_id: 11, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 5, taggable_id: 11, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 24, taggable_id: 12, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 25, taggable_id: 12, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 26, taggable_id: 12, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 27, taggable_id: 13, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 28, taggable_id: 14, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"}, {tag_id: 29, taggable_id: 14, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 30, taggable_id: 14, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 37, taggable_id: 17, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 12, taggable_id: 17, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 37, taggable_id: 18, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 12, taggable_id: 18, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 38, taggable_id: 18, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 11, taggable_id: 19, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 39, taggable_id: 19, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 40, taggable_id: 20, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 41, taggable_id: 20, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 42, taggable_id: 20, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 41, taggable_id: 22, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 1, taggable_id: 23, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 45, taggable_id: 23, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 46, taggable_id: 23, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 47, taggable_id: 24, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 48, taggable_id: 25, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 49, taggable_id: 26, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 4, taggable_id: 26, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 50, taggable_id: 26, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 51, taggable_id: 26, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 52, taggable_id: 26, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 13, taggable_id: 26, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 48, taggable_id: 27, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 53, taggable_id: 27, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 54, taggable_id: 27, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 49, taggable_id: 27, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 55, taggable_id: 10, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 56, taggable_id: 10, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 54, taggable_id: 17, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 57, taggable_id: 22, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 57, taggable_id: 20, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 58, taggable_id: 9, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 58, taggable_id: 18, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 58, taggable_id: 20, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 59, taggable_id: 10, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 60, taggable_id: 24, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 60, taggable_id: 23, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 61, taggable_id: 24, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 62, taggable_id: 13, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 62, taggable_id: 12, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 62, taggable_id: 25, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 63, taggable_id: 20, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 64, taggable_id: 10, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 64, taggable_id: 23, taggable_type: "Conversation", tagger_id: nil, tagger_type: nil, context: "tags"}
])

ActsAsTaggableOn::Tag.create!([
  {name: "401k", taggings_count: 1},
  {name: "saving", taggings_count: 1},
  {name: "investing", taggings_count: 0},
  {name: "APR", taggings_count: 1},
  {name: "interest rate", taggings_count: 1},
  {name: "retirement", taggings_count: 2},
  {name: "savings", taggings_count: 1},
  {name: "credit card", taggings_count: 2},
  {name: "dispute", taggings_count: 1},
  {name: "charges", taggings_count: 1},
  {name: "deposit", taggings_count: 1},
  {name: "check", taggings_count: 1},
  {name: "quick money", taggings_count: 1},
  {name: "help", taggings_count: 1},
  {name: "money", taggings_count: 1},
  {name: "bills", taggings_count: 1},
  {name: "auto loan", taggings_count: 1},
  {name: "cars", taggings_count: 1},
  {name: "owe", taggings_count: 1},
  {name: "vehicle", taggings_count: 1},
  {name: "car", taggings_count: 1},
  {name: "debt collector", taggings_count: 1},
  {name: "money transfer", taggings_count: 1},
  {name: "remittance transfer", taggings_count: 1},
  {name: "transfer", taggings_count: 1},
  {name: "monthly", taggings_count: 1},
  {name: "Budgeting", taggings_count: 1},
  {name: "payday", taggings_count: 2},
  {name: "loan", taggings_count: 3},
  {name: "fees", taggings_count: 1},
  {name: "student loan", taggings_count: 2},
  {name: "public service", taggings_count: 1},
  {name: "savings account", taggings_count: 1},
  {name: "child", taggings_count: 1},
  {name: "sending money", taggings_count: 0},
  {name: "international", taggings_count: 0},
  {name: "federal protections", taggings_count: 0},
  {name: "student loans", taggings_count: 1},
  {name: "lenders", taggings_count: 1},
  {name: "repayment", taggings_count: 1},
  {name: "college", taggings_count: 2},
  {name: "Credit score", taggings_count: 2},
  {name: "employment", taggings_count: 1},
  {name: "Loans", taggings_count: 2},
  {name: "debt", taggings_count: 1},
  {name: "credit", taggings_count: 1},
  {name: "score", taggings_count: 0},
  {name: "family", taggings_count: 1},
  {name: "friends", taggings_count: 1},
  {name: "private mortgage insurance", taggings_count: 0},
  {name: "mortgage", taggings_count: 0},
  {name: "insurance", taggings_count: 0},
  {name: "children", taggings_count: 2},
  {name: "broke", taggings_count: 0},
  {name: "shopping", taggings_count: 0},
  {name: "rent", taggings_count: 2},
  {name: "starting a family", taggings_count: 2},
  {name: "banking", taggings_count: 3},
  {name: "monthly bills", taggings_count: 1},
  {name: "managing money", taggings_count: 2},
  {name: "hopes and dreams", taggings_count: 1},
  {name: "stress", taggings_count: 3},
  {name: "marriage", taggings_count: 1},
  {name: "end of the month", taggings_count: 2}
])
